name: basement_music
description: Music player with the ability to download tracks from YouTube

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audio_service: ^0.18.9
  audioplayers: ^5.1.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0
  equatable: ^2.0.3
  file_picker: ^5.5.0
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  flex_color_scheme: ^6.0.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.0.8
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_dropzone: ^3.0.5
  flutter_search_bar: ^3.0.0-dev.1
  http: ^0.13.3
  http_parser: ^4.0.0
  hydrated_bloc: ^9.1.2
  js: ^0.6.4
  lint: ^2.1.2
  marquee_text: ^2.5.0+1
  path_provider: ^2.0.11
  shared_preferences: ^2.0.7
  sizer: ^2.0.15
  url_strategy: ^0.2.0
  uuid: ^3.0.7
  web_socket_channel: ^2.2.0
  youtube_metadata: ^1.0.0

dev_dependencies:
  flutter_native_splash: ^2.2.14
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  color: "#ffffff"
  image: assets/audio-waves.png

  color_dark: "#000000"
  image_dark: assets/audio-waves-colored.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
  