name: basement_music
description: Music player with the ability to download tracks from YouTube

publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  audio_service: ^0.18.12
  audioplayers: ^5.1.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  collection: ^1.17.2
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dotted_border: ^2.0.0
  equatable: ^2.0.3
  file_picker: ^5.5.0
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_dropzone: ^3.0.5
  flutter_search_bar: ^3.0.0-dev.1
  go_router: ^11.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.0
  http_parser: ^4.0.0
  hydrated_bloc: ^9.1.2
  js: ^0.6.4
  json_annotation: ^4.8.1
  lint: ^2.1.2
  logger: ^2.0.2
  marquee_text: ^2.5.0+1
  meta: ^1.9.1
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  rxdart: ^0.27.7
  sizer: ^2.0.15
  url_strategy: ^0.2.0
  uuid: ^3.0.7
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_native_splash: ^2.2.14
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1  
  retrofit_generator: ^8.0.3

flutter:
  assets:
    - assets/
    - shorebird.yaml
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/audio-waves.png

  color_dark: "#000000"
  image_dark: assets/audio-waves-colored.png

  android_12:
  