version: '3'
services:
  postgres:
    image: 'postgres:alpine3.16'
    container_name: postgres
    hostname: postgres
    ports:
      - $POSTGRES_EXTERNAL_PORT:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build:
      context: "./backend/"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: $POSTGRES_DB
      LISTEN_PORT: $LISTEN_PORT
      LISTEN_HOST: $LISTEN_HOST
      MUSIC_PATH: /server/music
    container_name: backend
    hostname: backend
    volumes:
      - ./backend/music:/server/music
    ports:
      - $LISTEN_PORT:$LISTEN_PORT
    depends_on:
      - postgres
  frontend:
    build:
      context: "./frontend/"
    container_name: frontend
    hostname: frontend
    ports:
      - $FRONTEND_PORT:8080
volumes:
  db-data:
    driver: local
