name: Web build and deploy

on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '1.29.2'
    - name: Create .env
      run: |
        tag_version=$(echo "${GITHUB_REF}" | cut -d'/' -f3)
        echo "${{ secrets.DOT_ENV_FILE }}" > .env
        echo "VERSION=${tag_version}" >> .env
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker images
      run: docker-compose build
    - name: Publish images
      run: docker-compose push
    - name: Copy docker-compose.yml
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "docker-compose.yml,.env"
        target: "basement-music"
    - name: Set up SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        envs: GITHUB_TOKEN
        script: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u lereena --password-stdin
          cd basement-music
          docker-compose pull
          docker-compose up -d --no-build
